apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-amd64
  labels:
    app: helloworld
    arch: amd64
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
      arch: amd64
  template:
    metadata:
      labels:
        app: helloworld
        arch: amd64
    spec:
      containers:
        - name: helloworld
          image: "ghcr.io/threadproc/hello-kubernetes:1.10"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: PORT
            value: "8080"
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CONTAINER_IMAGE
            value: "ghcr.io/threadproc/hello-kubernetes:1.10"
      nodeSelector:
        kubernetes.io/arch: amd64
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - helloworld
            topologyKey: "kubernetes.io/hostname"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-arm64
  labels:
    app: helloworld
    arch: arm64
spec:
  replicas: 8
  selector:
    matchLabels:
      app: helloworld
      arch: arm64
  template:
    metadata:
      labels:
        app: helloworld
        arch: arm64
    spec:
      containers:
        - name: helloworld
          image: "ghcr.io/threadproc/hello-kubernetes:1.10"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
          - name: PORT
            value: "8080"
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CONTAINER_IMAGE
            value: "ghcr.io/threadproc/hello-kubernetes:1.10"
      nodeSelector:
        kubernetes.io/arch: arm64
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - helloworld
            topologyKey: "kubernetes.io/hostname"
---

